name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --prefer-offline --frozen-lockfile
      - run: yarn format:check
      - run: yarn test -- --coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: yarn build
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain afraid-insect.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
